"""Answer key: workbook exercise ``plant-lockout`` (docs/workbook/plant-lockout.md).

The dataset is synthetic (``synthetic-hw-plant-lockout``, generated by CAMBER: 0.103, #133), so
the stand-in *is* the real data: :func:`standin` generates and ingests the catalog entry itself,
offline, and every expectation holds on both modes. Figures were recorded from::

    camber datasets fetch synthetic-hw-plant-lockout
    camber datasets ingest synthetic-hw-plant-lockout --store lab_store
    camber datasets config synthetic-hw-plant-lockout --exercise plant-lockout --store lab_store \
        --out lock.json
    camber run lock.json --out lock_out
    camber datasets score synthetic-hw-plant-lockout --store lab_store \
        --findings lock_out/findings.json

plus the ``plant-lockout--58f`` and ``plant-lockout--75f`` variants (CAMBER 0.103.0-dev,
2026-10-10).
"""

from __future__ import annotations

import os

from _workbook import Check, Exercise, Finding, Metric, Run, Score

from camber import datasets

_DS = "synthetic-hw-plant-lockout"
_BOILER, _PUMP = "boiler_summer_lockout", "hw_pump_summer_lockout"
_PLANTS = ("locked_out", "warm_spell", "pump_left_on", "low_lockout")


def standin(store) -> None:
    """The synthetic entry itself, generated into a cache beside the store and ingested."""
    cache = os.path.join(os.path.dirname(os.path.abspath(store.root)), "synthetic-cache")
    datasets.ingest(_DS, store.root, data_dir=cache)


def _pump_inherits(run: str, value: float):
    def check(ctx) -> None:
        """The variant sets the lockout on the boiler rule only; the pump rule judges every plant
        at the same value and records where it came from."""
        for plant in _PLANTS:
            f = ctx.finding(_PUMP, f"PLANT__{plant}", run)
            assert f is not None, f"no {_PUMP} finding on PLANT__{plant}"
            assert f.metrics["lockout_oat_f"] == value, f"{plant}: {f.metrics['lockout_oat_f']}"
            basis = (f.metrics.get("param_basis") or {}).get("summer_lockout_oat_f") or {}
            assert basis.get("value") == value, f"{plant}: param_basis {basis}"
            assert "inherited from boiler_summer_lockout" in str(basis.get("basis")), basis

    return check


def _pump_alone(ctx) -> None:
    """On PLANT__pump_left_on the pump runs every occupied hour, and in every one of its hours
    above the lockout the boiler is off."""
    f = ctx.finding(_PUMP, "PLANT__pump_left_on")
    assert f is not None, "no pump finding on PLANT__pump_left_on"
    assert f.metrics["pump_running_pct"] == 100.0, f.metrics
    assert f.metrics["boiler_off_pct"] == 100.0, f.metrics
    assert "boiler was off in 100%" in f.summary, f.summary


def _where_it_stops(ctx) -> None:
    """The warmest firing hour of each plant: 64.7 / 64.8 °F for the two plants locked out at
    65 °F, 58.0 °F for the low-lockout plant, 79.9 °F for the warm spell."""
    want = {"locked_out": 64.7, "pump_left_on": 64.8, "low_lockout": 58.0, "warm_spell": 79.9}
    for plant, top in want.items():
        f = ctx.finding(_BOILER, f"PLANT__{plant}")
        assert f is not None, f"no boiler finding on PLANT__{plant}"
        assert f.metrics["max_oat_running_f"] == top, f"{plant}: {f.metrics['max_oat_running_f']}"


EXERCISE = Exercise(
    id="plant-lockout",
    title="Heating plant lockout: a boiler and a pump left on in warm weather",
    issue=82,
    references=("pnnl-guide-plant-heating", "pnnl-retuning-ch8"),
    datasets=(_DS,),
    runs=(
        Run(dataset=_DS, config="plant-lockout"),
        Run(dataset=_DS, name="low", config="plant-lockout--58f"),
        Run(dataset=_DS, name="high", config="plant-lockout--75f"),
    ),
    commands=(
        "camber datasets fetch synthetic-hw-plant-lockout",
        "camber datasets ingest synthetic-hw-plant-lockout --store lab_store",
        "camber datasets config synthetic-hw-plant-lockout --exercise plant-lockout "
        "--store lab_store --out lock.json",
        "camber run lock.json --out lock_out",
        "camber datasets score synthetic-hw-plant-lockout --store lab_store "
        "--findings lock_out/findings.json",
        "camber datasets config synthetic-hw-plant-lockout --exercise plant-lockout--58f "
        "--store lab_store --out lock58.json",
        "camber run lock58.json --out lock58_out",
        "camber datasets config synthetic-hw-plant-lockout --exercise plant-lockout--75f "
        "--store lab_store --out lock75.json",
        "camber run lock75.json --out lock75_out",
    ),
    expect=(
        # 1. at 65 F: the warm-spell plant fails both rules, the pump-left-on plant the pump rule
        Finding(_BOILER, "PLANT__locked_out", severity=("ok",)),
        Finding(_PUMP, "PLANT__locked_out", severity=("ok",)),
        Finding(_BOILER, "PLANT__low_lockout", severity=("ok",)),
        Finding(_PUMP, "PLANT__low_lockout", severity=("ok",)),
        Finding(_BOILER, "PLANT__warm_spell", severity=("fault",)),
        Finding(_PUMP, "PLANT__warm_spell", severity=("fault",)),
        Finding(_BOILER, "PLANT__pump_left_on", severity=("ok",)),
        Finding(_PUMP, "PLANT__pump_left_on", severity=("fault",)),
        Metric(_BOILER, "PLANT__warm_spell", "summer_run_pct", 34.62, 0.005, quote="34.62%"),
        Metric(_PUMP, "PLANT__warm_spell", "summer_run_pct", 39.53, 0.005, quote="39.53%"),
        # 2. the pump on its own
        Metric(_PUMP, "PLANT__pump_left_on", "summer_run_pct", 70.45, 0.005, quote="70.45%"),
        Check("the pump runs alone, the boiler off", _pump_alone, quote="100%"),
        Metric(_PUMP, "PLANT__warm_spell", "boiler_off_pct", 36.47, 0.005, quote="36.47%"),
        # 3. the label score
        Score(_BOILER, tpr=1.0, fpr=0.0, quote="TPR 100%"),
        Score(_PUMP, tpr=1.0, fpr=0.0),
        # 4. at 58 F: the two plants locked out at 65 F now fail; the low-lockout plant passes
        Finding(_BOILER, "PLANT__locked_out", severity=("fault",), run="low"),
        Finding(_BOILER, "PLANT__pump_left_on", severity=("fault",), run="low"),
        Finding(_BOILER, "PLANT__low_lockout", severity=("ok",), run="low"),
        Finding(_PUMP, "PLANT__low_lockout", severity=("ok",), run="low"),
        Finding(_PUMP, "PLANT__locked_out", severity=("fault",), run="low"),
        Metric(
            _BOILER, "PLANT__locked_out", "summer_run_pct", 65.22, 0.005, run="low", quote="65.22%"
        ),
        Check("the pump rule inherits the 58 F lockout", _pump_inherits("low", 58.0)),
        # 5. at 75 F: the warm spell drops to a warn on the boiler; the pump still faults
        Finding(_BOILER, "PLANT__warm_spell", severity=("warn",), run="high"),
        Metric(
            _BOILER, "PLANT__warm_spell", "summer_run_pct", 17.95, 0.005, run="high", quote="17.95%"
        ),
        Finding(_PUMP, "PLANT__warm_spell", severity=("fault",), run="high"),
        Finding(_PUMP, "PLANT__pump_left_on", severity=("fault",), run="high"),
        Check("the pump rule inherits the 75 F lockout", _pump_inherits("high", 75.0)),
        # ... and where each plant stops firing
        Check("where each plant stops firing", _where_it_stops, quote="58.0 °F"),
        Metric(_BOILER, "PLANT__locked_out", "max_oat_running_f", 64.7, 0.0, quote="64.7 °F"),
    ),
    standin=standin,
)
