#!/usr/bin/env python3
"""Regenerate docs/THRESHOLDS.md from the rule-parameter registry (camber.rules.param_docs).

Every default is read from the rule constructors and every basis, unit, range and calibration
hint from ``camber/rules/param_docs.py``, so the page always says what the code does. Run it after
changing a rule parameter or its entry; ``--check`` exits 1 (without writing) when the page is out
of date, which ``tests/test_param_docs.py`` asserts too.

    python scripts/thresholds_doc.py          # rewrite docs/THRESHOLDS.md
    python scripts/thresholds_doc.py --check  # verify only
"""

from __future__ import annotations

import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from camber.rules import param_docs as pd  # noqa: E402

DOC = os.path.join(ROOT, "docs", "THRESHOLDS.md")

_INTRO = """\
# Rule thresholds

<!-- Generated by scripts/thresholds_doc.py from camber/rules/param_docs.py. Do not edit by hand:
change the registry (or the rule's constructor) and re-run the script. -->

Every tunable parameter of every built-in rule: its default (read from the rule's constructor),
its unit, a sensible range, **where the default comes from**, and how to re-tune it from your own
data. `camber rules params [RULE]` prints the same information in the terminal, with a
ready-to-paste config snippet (`--yaml` puts each basis and calibration hint beside its value as a
comment; `--json` is machine-readable).

**Changing a threshold.** Give the rule's entry in a run config `params`; only the ones you set
change, the rest keep their defaults:

```json
{"rules": [{"name": "leaking_valve", "params": {"fan_heat_f": 1.0}}]}
```

or, in a YAML config (the optional `[yaml]` extra), with the calibration recorded beside it:

```yaml
rules:
  - name: leaking_valve
    params:
      # calibrated on <site> AHU-1, 2026-03-01..03-31 (fan on, both valves closed):
      # median mixed-to-supply rise 1.0 F; scored on April-June, not on March
      fan_heat_f: 1.0
    basis:
      fan_heat_f: "calibrated on AHU-1 March 2026 (fan-on, valves closed)"
```

The optional `basis` map copies that provenance into each finding of the rule
(`metrics["param_basis"]`). How to calibrate without fooling yourself is in
[Tuning thresholds with your own data](TUNING.md).

**Basis** says where a default comes from:

- `standard: ...` -- the code cites that standard and section for the value;
- `public source: ...` -- a published, non-standard source (a PNNL Re-tuning guide chapter, a
  DOE or LBNL guide, a manufacturer convention);
- `CAMBER judgment` -- an engineering choice, usually screening-grade: re-tune it first;
- `calibrated on ...` -- fitted to the named dataset or run.

**Tier maps.** A parameter whose value is a dict of tiers (`{"warn": 5.0, "fault": 20.0}`) names
its keys in the unit column, and its range applies to each value ("each value: 0 to 100"); the
calibration note says how the keys must be ordered.

**Fixed in code** lists thresholds that are not constructor parameters yet, so you can see what
you cannot tune from a config today.

The registry is a provisional API (0.98): its shape may still change before 1.0.
"""


def _cell(text) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def _range(r: tuple, default=None, unit: str = "") -> str:
    if all(isinstance(v, (str, bool)) for v in r):
        return ", ".join(f"`{pd.json_value(v)}`" for v in r)
    each = "each value: " if pd._per_key(unit, default) else ""  # a tier map: the range per key
    words = "".join(f"`{pd.json_value(v)}`, or " for v in pd._keywords(r))  # keyword or number
    return f"{words}{each}{r[-2] if words else r[0]} to {r[-1]}"


def render_markdown() -> str:
    """The whole of docs/THRESHOLDS.md."""
    rules = pd.documented_rules()
    out = [_INTRO, "## Rules at a glance\n", "| Rule | Tunable parameters | Also fixed in code |"]
    out.append("|---|---|---|")
    for rule in rules:
        params = pd.rule_params(rule)
        n = f"{len(params)}" + (
            f" (passed to `{pd.DELEGATES[rule]}`)" if rule in pd.DELEGATES else ""
        )
        out.append(f"| [`{rule}`](#{rule}) | {n} | {'yes' if rule in pd.FIXED else ''} |")
    out.append("")
    for rule in rules:
        out.append(f"## {rule}\n")
        params = pd.rule_params(rule)
        if rule in pd.DELEGATES:
            out.append(
                f"Its parameters are passed through to [`{pd.DELEGATES[rule]}`]"
                f"(#{pd.DELEGATES[rule]}); set them on this rule's own entry.\n"
            )
        own = [rp for rp in params if not rp.delegated_from]
        if not params:
            out.append("No tunable parameters.\n")
        if own:
            out.append("| Parameter | Default | Unit | Range | Basis |")
            out.append("|---|---|---|---|---|")
            for rp in own:
                d = rp.doc
                out.append(
                    f"| `{rp.name}` | `{pd.json_value(rp.default)}` | {_cell(d.unit)} | "
                    f"{_cell(_range(d.range, rp.default, d.unit))} | {_cell(d.basis)} |"
                )
            out.append("")
            out.append("How to calibrate:\n")
            for rp in own:
                d = rp.doc
                line = f"- `{rp.name}`: {d.calibrate}"
                if d.note:
                    line += f" *Note:* {d.note}"
                out.append(line)
            out.append("")
        if rule in pd.EXEMPT:
            items = "; ".join(f"`{k}` ({v})" for k, v in pd.EXEMPT[rule].items())
            out.append(f"Not thresholds: {items}.\n")
        if rule in pd.FIXED:
            out.append(f"Fixed in code: {pd.FIXED[rule]}\n")
    return "\n".join(out).rstrip() + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="verify only; exit 1 if out of date")
    args = ap.parse_args(argv)
    new = render_markdown()
    try:
        with open(DOC, encoding="utf-8") as fh:
            text = fh.read()
    except FileNotFoundError:
        text = ""
    if new == text:
        print("docs/THRESHOLDS.md is up to date.")
        return 0
    if args.check:
        print("docs/THRESHOLDS.md is out of date: run scripts/thresholds_doc.py", file=sys.stderr)
        return 1
    with open(DOC, "w", encoding="utf-8") as fh:
        fh.write(new)
    print("rewrote docs/THRESHOLDS.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
